appName: demo-payment-service
image:
  repository: ghcr.io/psu-pennstateit-swe/demo-payment-service
  tag: 91d1344745d1d8984e21da200a80f0963bec22d7
  pullSecrets: ghcr-secret
ingress:
  hosts:
    - demo-payment-service.local
  paths:
    - /
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
linkerd:
  enabled: false
serviceProfile:
  enabled: false
serviceMonitor:
  enabled: false
oathkeeper:
  enabled: false
certificates:
  enabled: false
