appName: demo-payment-service
image:
  repository: ghcr.io/psu-pennstateit-swe/demo-payment-service
  tag: 88252299c39d40973bbcd16f4e6c6972b3beade8
  pullSecrets: ghcr-secret
ingress:
  hosts:
    - demo-payment-service.local
  paths:
    - /
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
linkerd:
  enabled: false
serviceProfile:
  enabled: false
serviceMonitor:
  enabled: false
oathkeeper:
  enabled: false
certificates:
  enabled: false
