appName: demo-payment-service
image:
  repository: ghcr.io/psu-pennstateit-swe/demo-payment-service
  tag: 88252299c39d40973bbcd16f4e6c6972b3beade8
  pullSecrets: ghcr-secret
ingress:
  hosts:
    - demo-payment-service.local
  paths:
    - /
livenessProbe:
  enabled: true
livenessProbePath: /actuator/health/liveness
livenessProbePort: 8080

readinessProbe:
  enabled: true
readinessProbePath: /actuator/health/readiness
readinessProbePort: 8080

javaParams: null

linkerd:
  enabled: false
serviceProfile:
  enabled: false
serviceMonitor:
  enabled: false
oathkeeper:
  enabled: false
certificates:
  enabled: false
