apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-boot-services
  namespace: management
spec:
  generators:
    - git:
        repoURL: https://github.com/matt328/bootstrap.git
        revision: main
        directories:
          - path: applications/overlays/*/*

  template:
    metadata:
      name: "{{path.basename}}-application"
      namespace: management
    spec:
      project: management

      destination:
        server: https://kubernetes.default.svc
        namespace: management

      sources:
        - repoURL: ghcr.io/psu-pennstateit-swe/charts
          chart: spring-boot
          targetRevision: 1.0.0
          helm:
            valueFiles:
              - values.yaml
