apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-boot-services
  namespace: management
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/matt328/bootstrap.git
        revision: main
        directories:
          - path: applications/*/*/*

  template:
    metadata:
      name: "{{index .path.segments 3}}-{{index .path.segments 2}}"
      namespace: management
    spec:
      project: management

      destination:
        server: https://kubernetes.default.svc
        namespace: management

      sources:
        - repoURL: ghcr.io/psu-pennstateit-swe/charts
          chart: spring-boot
          targetRevision: 1.0.0
          helm:
            valueFiles:
              - $values/base/{{.path.basename}}/values.yaml
              - $values/{{.path}}/values.yaml
        - repoURL: https://github.com/matt328/bootstrap.git
          targetRevision: main
          ref: values
