helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 9.0.6
    releaseName: argocd
    namespace: management
    valuesFile: values.yaml

resources:
  - service.yaml
